/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package accdbp.view;

import accdbp.controller.HomeCn;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Minami
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        psetting = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lCompanyLabel = new javax.swing.JLabel();
        mainHomePanel = new javax.swing.JPanel();
        container = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        bJournalGeneral = new javax.swing.JButton();
        bReport = new javax.swing.JButton();
        bReindex = new javax.swing.JButton();
        bBankPayments = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bJournalSale = new javax.swing.JButton();
        bHome = new javax.swing.JButton();
        bAccount = new javax.swing.JButton();
        bCashReceipts = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        bBankReceipts = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        bCashPayment = new javax.swing.JButton();
        bJournalPurchase = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lacc_periode = new javax.swing.JLabel();
        progressMain = new javax.swing.JProgressBar();
        lProgress = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        psetting.setBackground(new java.awt.Color(51, 51, 51));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/accdbp/icon/ic_settings_applications_white_18dp.png"))); // NOI18N
        jLabel16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        psetting.add(jLabel16);

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Setting");
        psetting.add(jLabel17);

        lCompanyLabel.setBackground(new java.awt.Color(255, 255, 255));
        lCompanyLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lCompanyLabel.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lCompanyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 613, Short.MAX_VALUE)
                .addComponent(psetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(psetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lCompanyLabel)
                .addContainerGap())
        );

        mainHomePanel.setBackground(new java.awt.Color(51, 51, 51));

        container.setBackground(new java.awt.Color(51, 51, 51));
        container.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        bJournalGeneral.setBackground(new java.awt.Color(51, 51, 51));
        bJournalGeneral.setFont(new java.awt.Font("AppleGothic", 1, 14)); // NOI18N
        bJournalGeneral.setForeground(new java.awt.Color(255, 255, 255));
        bJournalGeneral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/accdbp/icon/ic_today_white_18dp.png"))); // NOI18N
        bJournalGeneral.setText("General");
        bJournalGeneral.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);

        bReport.setBackground(new java.awt.Color(51, 51, 51));
        bReport.setFont(new java.awt.Font("AppleGothic", 1, 14)); // NOI18N
        bReport.setForeground(new java.awt.Color(255, 255, 255));
        bReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/accdbp/icon/ic_print_white_18dp.png"))); // NOI18N
        bReport.setText("Report");
        bReport.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);

        bReindex.setBackground(new java.awt.Color(51, 51, 51));
        bReindex.setFont(new java.awt.Font("AppleGothic", 1, 14)); // NOI18N
        bReindex.setForeground(new java.awt.Color(255, 255, 255));
        bReindex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/accdbp/icon/ic_lightbulb_outline_white_18dp.png"))); // NOI18N
        bReindex.setText("Re Index Data");
        bReindex.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);

        bBankPayments.setBackground(new java.awt.Color(51, 51, 51));
        bBankPayments.setFont(new java.awt.Font("AppleGothic", 1, 14)); // NOI18N
        bBankPayments.setForeground(new java.awt.Color(255, 255, 255));
        bBankPayments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/accdbp/icon/ic_payment_white_18dp.png"))); // NOI18N
        bBankPayments.setText("Bank Payments");
        bBankPayments.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);

        jLabel1.setFont(new java.awt.Font("AppleGothic", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Journals");

        bJournalSale.setBackground(new java.awt.Color(51, 51, 51));
        bJournalSale.setFont(new java.awt.Font("AppleGothic", 1, 14)); // NOI18N
        bJournalSale.setForeground(new java.awt.Color(255, 255, 255));
        bJournalSale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/accdbp/icon/ic_today_white_18dp.png"))); // NOI18N
        bJournalSale.setText("Sale");
        bJournalSale.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);

        bHome.setBackground(new java.awt.Color(51, 51, 51));
        bHome.setFont(new java.awt.Font("AppleGothic", 1, 14)); // NOI18N
        bHome.setForeground(new java.awt.Color(255, 255, 255));
        bHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/accdbp/icon/ic_home_white_18dp.png"))); // NOI18N
        bHome.setText("Home");
        bHome.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);

        bAccount.setBackground(new java.awt.Color(51, 51, 51));
        bAccount.setFont(new java.awt.Font("AppleGothic", 1, 14)); // NOI18N
        bAccount.setForeground(new java.awt.Color(255, 255, 255));
        bAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/accdbp/icon/ic_account_balance_wallet_white_18dp.png"))); // NOI18N
        bAccount.setText("Accounts");
        bAccount.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        bAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAccountActionPerformed(evt);
            }
        });

        bCashReceipts.setBackground(new java.awt.Color(51, 51, 51));
        bCashReceipts.setFont(new java.awt.Font("AppleGothic", 1, 14)); // NOI18N
        bCashReceipts.setForeground(new java.awt.Color(255, 255, 255));
        bCashReceipts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/accdbp/icon/ic_receipt_white_18dp.png"))); // NOI18N
        bCashReceipts.setText("Cash Receipts");
        bCashReceipts.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);

        jLabel5.setFont(new java.awt.Font("AppleGothic", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Payments");

        bBankReceipts.setBackground(new java.awt.Color(51, 51, 51));
        bBankReceipts.setFont(new java.awt.Font("AppleGothic", 1, 14)); // NOI18N
        bBankReceipts.setForeground(new java.awt.Color(255, 255, 255));
        bBankReceipts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/accdbp/icon/ic_credit_card_white_18dp.png"))); // NOI18N
        bBankReceipts.setText("Bank Receipts");
        bBankReceipts.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);

        jLabel4.setFont(new java.awt.Font("AppleGothic", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Receipts");

        bCashPayment.setBackground(new java.awt.Color(51, 51, 51));
        bCashPayment.setFont(new java.awt.Font("AppleGothic", 1, 14)); // NOI18N
        bCashPayment.setForeground(new java.awt.Color(255, 255, 255));
        bCashPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/accdbp/icon/ic_monetization_on_white_18dp.png"))); // NOI18N
        bCashPayment.setText("Cash Payments");
        bCashPayment.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);

        bJournalPurchase.setBackground(new java.awt.Color(51, 51, 51));
        bJournalPurchase.setFont(new java.awt.Font("AppleGothic", 1, 14)); // NOI18N
        bJournalPurchase.setForeground(new java.awt.Color(255, 255, 255));
        bJournalPurchase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/accdbp/icon/ic_today_white_18dp.png"))); // NOI18N
        bJournalPurchase.setText("Purchase");
        bJournalPurchase.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);

        jLabel8.setFont(new java.awt.Font("AppleGothic", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Other");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bBankPayments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bCashReceipts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bBankReceipts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bJournalSale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bJournalPurchase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bCashPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bJournalGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bReindex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(bHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bCashPayment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bBankPayments)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bCashReceipts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bBankReceipts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bJournalSale)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bJournalPurchase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bJournalGeneral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(7, 7, 7)
                .addComponent(bReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bReindex)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lacc_periode.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lacc_periode.setForeground(new java.awt.Color(255, 255, 255));
        lacc_periode.setText("Acounting Periode");

        progressMain.setBackground(new java.awt.Color(51, 51, 51));
        progressMain.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        progressMain.setForeground(new java.awt.Color(255, 255, 255));
        progressMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        lProgress.setBackground(new java.awt.Color(255, 255, 255));
        lProgress.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lProgress.setForeground(new java.awt.Color(255, 255, 255));
        lProgress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lProgress.setText("Processing Data");

        javax.swing.GroupLayout mainHomePanelLayout = new javax.swing.GroupLayout(mainHomePanel);
        mainHomePanel.setLayout(mainHomePanelLayout);
        mainHomePanelLayout.setHorizontalGroup(
            mainHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainHomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lacc_periode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainHomePanelLayout.createSequentialGroup()
                        .addComponent(progressMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lProgress))
                    .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainHomePanelLayout.setVerticalGroup(
            mainHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainHomePanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(mainHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lacc_periode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progressMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lProgress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainHomePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainHomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bAccount;
    public javax.swing.JButton bBankPayments;
    public javax.swing.JButton bBankReceipts;
    public javax.swing.JButton bCashPayment;
    public javax.swing.JButton bCashReceipts;
    public javax.swing.JButton bHome;
    public javax.swing.JButton bJournalGeneral;
    public javax.swing.JButton bJournalPurchase;
    public javax.swing.JButton bJournalSale;
    public javax.swing.JButton bReindex;
    public javax.swing.JButton bReport;
    public javax.swing.JPanel container;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JLabel lCompanyLabel;
    public javax.swing.JLabel lProgress;
    public javax.swing.JLabel lacc_periode;
    public javax.swing.JPanel mainHomePanel;
    public javax.swing.JProgressBar progressMain;
    public javax.swing.JPanel psetting;
    // End of variables declaration//GEN-END:variables
}
